### ISSUE TITLE
why run_export_onnx.sh --weights is xxx.onnx not xxx.pt?

### ISSUE THREAD

**Issue by dsp6414** [anhnktp/yolov5_openvino#1]
export PYTHONPATH="$PWD"
python conversion/export.py \
       --weights /Users/anhvu/Downloads/untitled_folder/best_best_m2_mix_person.onnx \
       --img-size 512 \
       --batch-size 1 \
       --out-dir weights/onnx

**Comment by anhnktp** [comment]
hi @dsp6414,
