### ISSUE TITLE
The problem of shape

### ISSUE THREAD

**Issue by YexiongLin** [anhnktp/yolov5_openvino#2]
I want to convert yolov5s.pt to openvino, I have converted to onnx, but when I try to convert onnx to openvino, this error happen. But the shape I convert to onnx and try to convert to  openvino are default(512).

[ 2020-09-15 11:54:45,141 ] [ DEBUG ] [ infer:145 ]  Outputs:
[ 2020-09-15 11:54:45,142 ] [ DEBUG ] [ infer:32 ]  output[0]: shape = [ 1  3 64 64  2], value = <UNKNOWN>
[ 2020-09-15 11:54:45,142 ] [ DEBUG ] [ infer:129 ]  --------------------
[ 2020-09-15 11:54:45,142 ] [ DEBUG ] [ infer:130 ]  Partial infer for Mul_229
[ 2020-09-15 11:54:45,142 ] [ DEBUG ] [ infer:131 ]  Op: Mul
[ 2020-09-15 11:54:45,142 ] [ DEBUG ] [ infer:132 ]  Inputs:
[ 2020-09-15 11:54:45,142 ] [ DEBUG ] [ infer:32 ]  input[0]: shape = [ 1  3 64 64  2], value = <UNKNOWN>
[ 2020-09-15 11:54:45,142 ] [ DEBUG ] [ infer:32 ]  input[1]: shape = [], value = 8.0
[ 2020-09-15 11:54:45,142 ] [ DEBUG ] [ infer:145 ]  Outputs:
[ 2020-09-15 11:54:45,143 ] [ DEBUG ] [ infer:32 ]  output[0]: shape = [ 1  3 64 64  2], value = <UNKNOWN>
[ 2020-09-15 11:54:45,143 ] [ DEBUG ] [ infer:129 ]  --------------------
[ 2020-09-15 11:54:45,143 ] [ DEBUG ] [ infer:130 ]  Partial infer for Concat_244
[ 2020-09-15 11:54:45,143 ] [ DEBUG ] [ infer:131 ]  Op: Concat
[ 2020-09-15 11:54:45,143 ] [ DEBUG ] [ infer:132 ]  Inputs:
[ 2020-09-15 11:54:45,143 ] [ DEBUG ] [ infer:32 ]  input[0]: shape = [ 1  3 64 64  2], value = <UNKNOWN>
[ 2020-09-15 11:54:45,143 ] [ DEBUG ] [ infer:32 ]  input[1]: shape = [ 1  1  3 64 64  2], value = <UNKNOWN>
[ 2020-09-15 11:54:45,143 ] [ DEBUG ] [ infer:32 ]  input[2]: shape = [ 1  3 64 64 81], value = <UNKNOWN>
[ ERROR ]  Cannot infer shapes or values for node "Concat_244".
[ ERROR ]  boolean index did not match indexed array along dimension 0; dimension is 6 but corresponding boolean dimension is 5
[ ERROR ]  
[ ERROR ]  It can happen due to bug in custom shape infer function <function concat_infer at 0x7fab30f04af0>.
[ ERROR ]  Or because the node inputs have incorrect values/shapes.
[ ERROR ]  Or because input shapes are incorrect (embedded to the model or passed via --input_shape).
[ 2020-09-15 11:54:45,145 ] [ DEBUG ] [ infer:197 ]  Node "Concat_244" attributes: {'pb': input: "416"
input: "429"
input: "434"
output: "435"
name: "Concat_244"
op_type: "Concat"
attribute {
  name: "axis"
  i: 4
  type: INT
}
, 'kind': 'op', '_in_ports': {0: {'control_flow': False}, 1: {'control_flow': False}, 2: {'control_flow': False}}, '_out_ports': {0: {'control_flow': False}}, 'name': 'Concat_244', 'op': 'Concat', 'type': 'Concat', 'axis': 4, 'infer': <function concat_infer at 0x7fab30f04af0>, 'IE': [('layer', [('id', <function update_ie_fields.<locals>.<lambda> at 0x7fab30940280>), 'name', 'type', 'version'], [('data', ['auto_pad', 'epsilon', 'min', 'max', ('axis', <function update_ie_fields.<locals>.<lambda> at 0x7fab30940310>), 'tiles', ('dim', <function update_ie_fields.<locals>.<lambda> at 0x7fab309403a0>), 'num_axes', ('pool-method', 'pool_method'), 'group', ('rounding-type', 'rounding_type'), ('exclude-pad', 'exclude_pad'), 'operation', 'out-size', 'power', 'shift', 'alpha', 'beta', 'coords', 'classes', 'num', ('local-size', 'local_size'), 'region', 'knorm', 'bias', 'num_classes', 'keep_top_k', 'variance_encoded_in_target', 'code_type', 'share_location', 'nms_threshold', 'confidence_threshold', 'background_label_id', 'top_k', 'eta', 'visualize', 'visualize_threshold', 'save_file', 'output_directory', 'output_name_prefix', 'output_format', 'label_map_file', 'name_size_file', 'num_test_image', 'prob', 'resize_mode', 'height', 'width', 'height_scale', 'width_scale', 'pad_mode', 'pad_value', 'interp_mode', 'img_size', 'img_h', 'img_w', 'step', 'step_h', 'step_w', ('offset', <function update_ie_fields.<locals>.<lambda> at 0x7fab30940430>), 'variance', 'flip', 'clip', ('min_size', <function update_ie_fields.<locals>.<lambda> at 0x7fab309404c0>), ('max_size', <function update_ie_fields.<locals>.<lambda> at 0x7fab30940550>), ('aspect_ratio', <function update_ie_fields.<locals>.<lambda> at 0x7fab309405e0>), 'decrease_label_id', 'normalized', 'scale_all_sizes', ('type', 'norm_type'), 'eps', 'eps_mode', 'across_spatial', 'channel_shared', 'negative_slope', 'engine', 'num_filter', ('type', 'sample_type'), ('order', <function update_ie_fields.<locals>.<lambda> at 0x7fab30940670>), 'pooled_h', 'pooled_w', 'spatial_scale', 'cls_threshold', 'max_num_proposals', 'iou_threshold', 'min_bbox_size', 'feat_stride', 'pre_nms_topn', 'post_nms_topn', ('type', <function update_ie_fields.<locals>.<lambda> at 0x7fab30940700>), ('value', <function update_ie_fields.<locals>.<lambda> at 0x7fab3093e040>), ('output', <function update_ie_fields.<locals>.<lambda> at 0x7fab3093e0d0>), ('input_nodes_names', <function update_ie_fields.<locals>.<lambda> at 0x7fab3093e160>), ('output_tensors_names', <function update_ie_fields.<locals>.<lambda> at 0x7fab3093e1f0>), ('real_input_dims', <function update_ie_fields.<locals>.<lambda> at 0x7fab3093e280>), ('protobuf', <function update_ie_fields.<locals>.<lambda> at 0x7fab3093e310>), {'custom_attributes': None}, ('strides', <function update_ie_fields.<locals>.<lambda> at 0x7fab3093ee50>), ('kernel', <function update_ie_fields.<locals>.<lambda> at 0x7fab308cad30>), ('dilations', <function update_ie_fields.<locals>.<lambda> at 0x7fab308cab80>), ('pads_begin', <function update_ie_fields.<locals>.<lambda> at 0x7fab308ca040>), ('pads_end', <function update_ie_fields.<locals>.<lambda> at 0x7fab308d0d30>), ('scale', <function update_ie_fields.<locals>.<lambda> at 0x7fab308d0af0>), 'crop_width', 'crop_height', 'write_augmented', 'max_multiplier', 'augment_during_test', 'recompute_mean', 'write_mean', 'mean_per_pixel', 'mode', 'bottomwidth', 'bottomheight', 'chromatic_eigvec', 'kernel_size', 'max_displacement', 'stride_1', 'stride_2', 'single_direction', 'do_abs', 'correlation_type', 'antialias', 'resample_type', 'factor', 'coeff', ('ratio', <function update_ie_fields.<locals>.<lambda> at 0x7fab308d0b80>), 'size'], []), '@ports', '@consts'])], 'dim_attrs': ['channel_dims', 'batch_dims', 'axis', 'spatial_dims'], 'shape_attrs': ['window', 'shape', 'output_shape', 'stride', 'pad'], 'is_output_reachable': True, 'is_undead': False, 'is_const_producer': False, 'is_partial_inferred': False}
[ ERROR ]  Exception occurred during running replacer "REPLACEMENT_ID" (<class 'extensions.middle.PartialInfer.PartialInfer'>): Stopped shape/value propagation at "Concat_244" node. 
 For more information please refer to Model Optimizer FAQ (https://docs.openvinotoolkit.org/latest/_docs_MO_DG_prepare_model_Model_Optimizer_FAQ.html), question #38. 
[ 2020-09-15 11:54:45,146 ] [ DEBUG ] [ main:322 ]  Traceback (most recent call last):
  File "/opt/intel/openvino_2020.4.287/deployment_tools/model_optimizer/mo/middle/passes/infer.py", line 135, in partial_infer
    node.infer(node)
  File "/opt/intel/openvino_2020.4.287/deployment_tools/model_optimizer/mo/front/common/partial_infer/concat.py", line 54, in concat_infer
    if np.all(shape[not_mask] == s[not_mask]):  # TODO handle -1 in a special way
IndexError: boolean index did not match indexed array along dimension 0; dimension is 6 but corresponding boolean dimension is 5

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/intel/openvino_2020.4.287/deployment_tools/model_optimizer/mo/utils/class_registration.py", line 288, in apply_transform
    for_graph_and_each_sub_graph_recursively(graph, replacer.find_and_replace_pattern)
  File "/opt/intel/openvino_2020.4.287/deployment_tools/model_optimizer/mo/middle/pattern_match.py", line 58, in for_graph_and_each_sub_graph_recursively
    func(graph)
  File "/opt/intel/openvino_2020.4.287/deployment_tools/model_optimizer/extensions/middle/PartialInfer.py", line 32, in find_and_replace_pattern
    partial_infer(graph)
  File "/opt/intel/openvino_2020.4.287/deployment_tools/model_optimizer/mo/middle/passes/infer.py", line 198, in partial_infer
    raise Error('Stopped shape/value propagation at "{}" node. '.format(node.soft_get('name')) +
mo.utils.error.Error: Stopped shape/value propagation at "Concat_244" node. 
 For more information please refer to Model Optimizer FAQ (https://docs.openvinotoolkit.org/latest/_docs_MO_DG_prepare_model_Model_Optimizer_FAQ.html), question #38. 

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/intel/openvino_2020.4.287/deployment_tools/model_optimizer/mo/main.py", line 309, in main
    ret_code = driver(argv)
  File "/opt/intel/openvino_2020.4.287/deployment_tools/model_optimizer/mo/main.py", line 270, in driver
    ret_res = emit_ir(prepare_ir(argv), argv)
  File "/opt/intel/openvino_2020.4.287/deployment_tools/model_optimizer/mo/main.py", line 235, in prepare_ir
    graph = unified_pipeline(argv)
  File "/opt/intel/openvino_2020.4.287/deployment_tools/model_optimizer/mo/pipeline/unified.py", line 25, in unified_pipeline
    class_registration.apply_replacements(graph, [
  File "/opt/intel/openvino_2020.4.287/deployment_tools/model_optimizer/mo/utils/class_registration.py", line 334, in apply_replacements
    apply_replacements_list(graph, replacers_order)
  File "/opt/intel/openvino_2020.4.287/deployment_tools/model_optimizer/mo/utils/class_registration.py", line 320, in apply_replacements_list
    apply_transform(
  File "/opt/intel/openvino_2020.4.287/deployment_tools/model_optimizer/mo/utils/logger.py", line 124, in wrapper
    function(*args, **kwargs)
  File "/opt/intel/openvino_2020.4.287/deployment_tools/model_optimizer/mo/utils/class_registration.py", line 300, in apply_transform
    raise Error('Exception occurred during running replacer "{}" ({}): {}'.format(
mo.utils.error.Error: Exception occurred during running replacer "REPLACEMENT_ID" (<class 'extensions.middle.PartialInfer.PartialInfer'>): Stopped shape/value propagation at "Concat_244" node. 
 For more information please refer to Model Optimizer FAQ (https://docs.openvinotoolkit.org/latest/_docs_MO_DG_prepare_model_Model_Optimizer_FAQ.html), question #38.

**Comment by anhnktp** [comment]
@YexiongLin which is your YOLOv5s model from ? You should choose the YOLOv5 models on version 2.0
